Cards
uclaacm/committee-website-template-cms pull request #13
Opened 2023-03-02 00:48 UTC by andyren12

2023-03-02 00:59 UTC, elizabethkim11 reviewed
lgtm! :D

2023-03-03 21:43 UTC, nendow02 requested changes
Looks great! Only one small change, lmk if you have different ideas on how to approach this too.

2023-03-03 21:43 UTC, nendow02 commented on styles/BoardCard.module.scss
> +  width: 450px;
Can we change the dimensions of the cards when the page becomes smaller than a certain size. My main issue is when only one column can fit, leaving a lot of white space like below. `@media` css property should be able to help you with this change.
![image](https://user-images.githubusercontent.com/35786272/222833600-3e5995a5-074f-4d69-8520-44a6ecf813db.png)

2023-05-14 04:09 UTC, ArshMalik02 commented
Looks good! Merging.

2023-05-14 04:09 UTC, merged