Footer
uclaacm/committee-website-template-cms pull request #14
Opened 2023-03-02 01:47 UTC by elizabethkim11

Footer w/ social icons + corresponding links

2023-03-03 21:16 UTC, nendow02 commented
Fixed the default mail icon issue, more info on the CSS I used can be found [here](https://developer.mozilla.org/en-US/docs/Web/CSS/::before). Lmk if you have any questions on what changed. I’ll review your PR rn.

2023-03-03 21:22 UTC, nendow02 requested changes
Nice job! Few requested changes one of which is moving css for footer into its own file. For the style changes those are more of suggestions, this is your ticket so if you have other ideas on these requests feel free to comment that!

2023-03-03 21:22 UTC, nendow02 commented on styles/Home.module.scss
> -.footer {
Can we put all of your footer css in its own module?

2023-03-03 21:22 UTC, nendow02 commented on styles/Home.module.scss
> +  margin-top: 03rem;
Can we remove margin-top here to make footer slightly smaller

2023-03-03 21:22 UTC, nendow02 commented on styles/Home.module.scss
> +  padding: 1rem 2rem;
Can we also remove top padding here (keep all others)

2023-03-07 04:25 UTC, andyren12 approved these changes
looks good

2023-03-07 04:27 UTC, nendow02 approved these changes
Go ahead and squash and merge!

2023-03-07 04:28 UTC, merged